api:
  insecure: true # decides whether the dashboard is enabled or not (on port 8080). set to false in production
  dashboard: true

providers:
  docker:
    exposedByDefault: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

certificatesResolvers:
  staging:
    acme:
      email: youremail@email.com # put your email here
      storage: /ssl-certs/dev/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web
  # production:
  #   acme:
  #     email: youremail@email.com
  #     storage: /ssl-certs/prod/acme.json
  #     caServer: "https://acme-v02.api.letsencrypt.org/directory"
  #     httpChallenge:
  #       entryPoint: web


